apiVersion: batch/v1
kind: Job
metadata:
  name: app-ga-loadtest
  namespace: default
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: loadtest
        image: app-ga-loadtest:latest
        imagePullPolicy: Never
        env:
        - name: TARGET_URL
          value: "http://app-ga.default.svc.cluster.local:8080"
        - name: DURATION
          value: "60"
        - name: CONCURRENCY
          value: "20"
        - name: LOG_LEVEL
          value: "DEBUG"
